#Cuadernos de Jupyter Notebooks
<p align="justify">Jupyter Notebook es una herramienta interactiva y de código abierto diseñada para crear y compartir documentos que contienen código ejecutable, texto formateado, visualizaciones y otros elementos multimedia. Es especialmente popular en los campos de la ciencia de datos, la inteligencia artificial y la investigación académica, ya que permite combinar código y documentación en un solo documento.</p>


##Características principales:
  1. Celdas interactivas:
        a. Los documentos están compuestos por celdas que pueden contener:
            i. Código: Ejecutable en tiempo real.
            ii. Texto: Escrito en Markdown para documentación, con soporte para ecuaciones en LaTeX.
            iii. Resultados: Gráficas, tablas y salidas del código ejecutado.
  2. Compatibilidad con múltiples lenguajes:
        a. Aunque está diseñado principalmente para Python, también soporta otros lenguajes mediante kernels (por ejemplo, R, Julia, C++, entre otros).
  3. Entorno flexible:
          a. Permite probar fragmentos de código sin necesidad de compilar un programa completo.
          b. Es ideal para análisis exploratorio de datos y prototipado de modelos.

#COLAB en particular
1. Entorno similar a Jupyter Notebook:
        a. Google Colab utiliza un formato de notebook, donde puedes combinar celdas de código ejecutable con texto en Markdown y ecuaciones en LaTeX.
2. Ejecución en la nube:
        a. Los notebooks se ejecutan en servidores remotos de Google, lo que significa que no necesitas una computadora potente para trabajar en proyectos exigentes.
        b. Ofrece acceso gratuito a hardware acelerado, como GPUs y TPUs.
3. Acceso gratuito:
        a. Google Colab es completamente gratuito, aunque también tiene una versión de pago (Colab Pro) que ofrece más recursos, como tiempos de ejecución más largos y acceso prioritario a GPUs.
4. Integración con Google Drive:
        a. Los notebooks se guardan automáticamente en Google Drive, lo que facilita su acceso, edición y colaboración en tiempo real con otros usuarios.
5. Compatibilidad con bibliotecas populares:
        a. Incluye bibliotecas preinstaladas como NumPy, Pandas, TensorFlow, PyTorch, Matplotlib, entre otras. También puedes instalar otras bibliotecas usando pip.

#Ejemplo de imagen
<img src='https://pbs.twimg.com/media/FUIh6EEXwAApjae.jpg'>

#Ejemplo Latex

$\int^{∞}_{-\infty}\frac{1}{\sqrt{2\sigma^{2}\pi }}e^{-\frac{(x-\mu)^{2}}{2\sigma^{2}}}$

#Python
<p align="justify">Python es un lenguaje de programación de alto nivel, conocido por su simplicidad y legibilidad. Sus ventajas incluyen una sintaxis clara, una amplia comunidad y numerosas bibliotecas, lo que lo hace ideal para principiantes y expertos. Sin embargo, su naturaleza interpretada puede resultar en una menor velocidad de ejecución en comparación con lenguajes compilados.
</p>

Características de Python
  * Lenguaje Interpretado: Python ejecuta el código línea por línea, lo que facilita la detección de errores.
  * Sintaxis Sencilla: Utiliza una sintaxis similar al inglés, lo que lo hace intuitivo y fácil de aprender.
  * Multiparadigma: Soporta programación orientada a objetos, estructurada y funcional.
  * Bibliotecas y Frameworks: Cuenta con una extensa biblioteca estándar y muchas bibliotecas de terceros para diversas aplicaciones.


#PIP!

Python Pip (abreviatura de Pip Installs Packages) es el gestor de paquetes oficial de Python. Permite instalar, actualizar y gestionar bibliotecas y paquetes desarrollados en Python, facilitando el acceso a un vasto ecosistema de herramientas y módulos disponibles en el Python Package Index (PyPI).

Características principales:
  1. Instalación de paquetes:
        * Pip descarga e instala automáticamente paquetes de PyPI y sus dependencias necesarias.
        * Ejemplo:
        * Se ejecuta en la terminal (Linux/mac) o símbolo del sistema (windows).
        *  pip install numpy
        * Esto instalará el paquete numpy y cualquier otra biblioteca que este requiera.
  2. Actualización de paquetes:
    * Permite actualizar las versiones de los paquetes instalados.
    * Ejemplo:
    * pip install –upgrade pandas

  3. Desinstalación de paquetes:
    * También puede eliminar paquetes instalados.
Ejemplo:
    * pip uninstall matplotlib

In [3]:
!pip install pprintpp

#Variables
<p align="justify">Una variable en un lenguaje de programación es un espacio de almacenamiento que se utiliza para guardar datos que pueden cambiar durante la ejecución de un programa. Las variables permiten a los programadores almacenar información, manipularla y acceder a ella de manera eficiente. A continuación, se detallan algunos aspectos clave sobre las variables:</p>

Declaración y Asignación
  * Declaración: En muchos lenguajes, se debe declarar una variable antes de usarla. Esto puede implicar especificar su tipo (por ejemplo, entero, cadena, etc.) o simplemente asignarle un valor.
  * Asignación: Se asigna un valor a la variable utilizando el operador de asignación (por ejemplo, = en Python).

In [4]:
edad = 25
nombre = "Ana"
altura = 1.65

print("Nombre: ", nombre)
print("Edad: ", edad)
print("Altura: ", altura)

Nombre:  Ana
Edad:  25
Altura:  1.65


modificando una variable

In [5]:
edad += 1
print("Nueva edad: ",edad)

Nueva edad:  26


##Tipos de datos básicos

Python tiene los mismos datos básicos que otros lenguajes: enteros, flotantes, strings y booleanos. Además, las listas son un tipo predefinido en el lenguaje.

In [6]:
#Enteros
X = 1

In [7]:
#Flotante
Y = 3.5

In [8]:
#Booleanos
A = True

In [9]:
#Listas
lista = [1,2,3.4,6,'algo']

In [10]:
print("X: ",X)
print("Y: ",Y)
print("A: ",A)
print("lista: ",lista)

X:  1
Y:  3.5
A:  True
lista:  [1, 2, 3.4, 6, 'algo']


## Más sobre listas
  1. Ordenadas: Los elementos en una lista tienen un orden específico, lo que significa que se pueden acceder a ellos mediante su índice (posición en la lista).
  2. Mutables: Las listas son mutables, lo que significa que puedes modificar su contenido después de haberlas creado. Puedes agregar, eliminar o cambiar elementos.
  3. Pueden Contener Diferentes Tipos de Datos: Una lista puede contener elementos de diferentes tipos, como números, cadenas, booleanos, e incluso otras listas.
  4. Indexación: Los índices en Python comienzan en 0, lo que significa que el primer elemento de la lista se encuentra en la posición 0, el segundo en la posición 1, y así sucesivamente.

In [11]:
#ingresando al elemento con una cadena de texto de la lista
print("Cadena: ",lista[4])

Cadena:  algo


In [12]:
print("Cadena: ",lista[-2])

Cadena:  6


In [13]:
lista.append('Jose')
print(lista)

[1, 2, 3.4, 6, 'algo', 'Jose']


In [14]:
#ingresando al elemento flotante
print("Float: ",lista[2])

Float:  3.4


#Estructuras de control en python

<p = align="justify">Las estructuras de control en Python son herramientas que permiten modificar el flujo de ejecución de un programa. Estas estructuras permiten tomar decisiones, repetir acciones y gestionar el flujo de datos, lo que es fundamental para crear programas que respondan a diferentes condiciones y realicen tareas de manera eficiente.</p>

Tipos de Estructuras de Control
  1. Estructuras de Control de Selección (Condicionales): Estas estructuras permiten ejecutar diferentes bloques de código según si se cumplen o no ciertas condiciones.
    1. if: Ejecuta un bloque de código si la condición es verdadera.
    2. elif: Permite verificar múltiples condiciones. Se utiliza después de un if.
    3. else: Se ejecuta si ninguna de las condiciones anteriores es verdadera.

In [15]:
edad = 38

if edad < 18:
  acum = 1+1
  print("Eres menor de edad")
elif edad == 18:
  print("Eres mayor de edad")
else:
  print("Eres un viejillo")

Eres un viejillo


2. Estructuras de Control de Repetición (Bucles): Estas estructuras permiten ejecutar un bloque de código varias veces.
    * for: Se utiliza para iterar sobre una secuencia (como una lista, tupla o cadena).
    * while: Ejecuta un bloque de código mientras una condición sea verdadera.

In [16]:
[*range(5)]

[0, 1, 2, 3, 4]

In [17]:
lista = [3,4,7,9,10]
for i in lista:
  print(i)

3
4
7
9
10


In [18]:
for i in range(5):
  print(i)

0
1
2
3
4


In [19]:
for i in range(edad):
  print(f"Tienes: {i+1} años")

Tienes: 1 años
Tienes: 2 años
Tienes: 3 años
Tienes: 4 años
Tienes: 5 años
Tienes: 6 años
Tienes: 7 años
Tienes: 8 años
Tienes: 9 años
Tienes: 10 años
Tienes: 11 años
Tienes: 12 años
Tienes: 13 años
Tienes: 14 años
Tienes: 15 años
Tienes: 16 años
Tienes: 17 años
Tienes: 18 años
Tienes: 19 años
Tienes: 20 años
Tienes: 21 años
Tienes: 22 años
Tienes: 23 años
Tienes: 24 años
Tienes: 25 años
Tienes: 26 años
Tienes: 27 años
Tienes: 28 años
Tienes: 29 años
Tienes: 30 años
Tienes: 31 años
Tienes: 32 años
Tienes: 33 años
Tienes: 34 años
Tienes: 35 años
Tienes: 36 años
Tienes: 37 años
Tienes: 38 años


In [20]:
#WHILE
contador = 0
while contador < 5:
  print(contador)
  contador+=1

0
1
2
3
4


In [21]:
contador = 1
while contador <= edad:
  print(f"Aun entra al ciclo por que tienes: {contador} años")
  contador+=1


Aun entra al ciclo por que tienes: 1 años
Aun entra al ciclo por que tienes: 2 años
Aun entra al ciclo por que tienes: 3 años
Aun entra al ciclo por que tienes: 4 años
Aun entra al ciclo por que tienes: 5 años
Aun entra al ciclo por que tienes: 6 años
Aun entra al ciclo por que tienes: 7 años
Aun entra al ciclo por que tienes: 8 años
Aun entra al ciclo por que tienes: 9 años
Aun entra al ciclo por que tienes: 10 años
Aun entra al ciclo por que tienes: 11 años
Aun entra al ciclo por que tienes: 12 años
Aun entra al ciclo por que tienes: 13 años
Aun entra al ciclo por que tienes: 14 años
Aun entra al ciclo por que tienes: 15 años
Aun entra al ciclo por que tienes: 16 años
Aun entra al ciclo por que tienes: 17 años
Aun entra al ciclo por que tienes: 18 años
Aun entra al ciclo por que tienes: 19 años
Aun entra al ciclo por que tienes: 20 años
Aun entra al ciclo por que tienes: 21 años
Aun entra al ciclo por que tienes: 22 años
Aun entra al ciclo por que tienes: 23 años
Aun entra al ciclo p

3. Estructuras de Control de Salida: Estas estructuras permiten salir de un bucle o función antes de que se complete su ejecución.
 * break: Termina el bucle actual y sale de él.
 * continue: Salta a la siguiente iteración del bucle, omitiendo el resto del código en la iteración actual.
 * return: Sale de una función y opcionalmente devuelve un valor.

In [22]:
for i in range(10):
  if i == 5:
    print("\n Se va a salir del bucle \n")
    break #Sale del bucle
  print(i)

0
1
2
3
4

 Se va a salir del bucle 



In [23]:
#Continue
for i in range(10):
  if i == 2:
    continue # Salta cuando la i == 2
  print(i)

0
1
3
4
5
6
7
8
9


¿Para Qué Sirven las Estructuras de Control?
Las estructuras de control son fundamentales en la programación porque:
  * Toman Decisiones: Permiten que el programa responda a diferentes condiciones y situaciones, lo que es esencial para la lógica de negocio.
  * Repetición de Tareas: Facilitan la ejecución de tareas repetitivas sin necesidad de duplicar código, lo que mejora la eficiencia y la legibilidad.
  * Control del Flujo: Permiten gestionar cómo y cuándo se ejecutan diferentes partes del código, lo que es crucial para el desarrollo de algoritmos complejos.
  * Manejo de Errores: Junto con otras estructuras, como try y except, permiten manejar excepciones y errores de manera controlada.

##Funciones

<p = align="justify">Las funciones en Python son bloques de código reutilizables que realizan una tarea específica. Se definen una vez y se pueden llamar múltiples veces a lo largo de un programa, lo que ayuda a organizar el código, mejorar su legibilidad y facilitar su mantenimiento. Las funciones pueden aceptar parámetros (entradas) y pueden devolver valores (salidas).</p>

¿Qué son las Funciones?
  1. Definición: Una función es un conjunto de instrucciones que se agrupan bajo un nombre específico. Se define utilizando la palabra clave def, seguida del nombre de la función y paréntesis que pueden incluir parámetros.
  2. Parámetros: Las funciones pueden aceptar entradas, conocidas como parámetros o argumentos. Estos permiten que la función opere sobre diferentes datos.
  3. Valor de Retorno: Las funciones pueden devolver un valor utilizando la palabra clave return. Si no se especifica un valor de retorno, la función devolverá None por defecto.

In [24]:
#Simple regla de 3
def calif(aciertos,reactivos):
  cal = (aciertos*10)/reactivos
  return cal

#Ejemplo
aciertos = 4
reactivos = 6
print(f"\nCalificación final: {calif(aciertos,reactivos)}\n")


Calificación final: 6.666666666666667



##Otra función

In [25]:
def sumar(a,b):
  resultado = a+b
  return resultado

suma = sumar(5,3)
print(suma)

8


##Más complicado

In [26]:
def sumar(lista):
  acum=0
  for i in range(len(lista)):
    acum=acum+lista[i]
  return acum

listax = [1,2,3,4,5,6,7,8]
print(sumar(listax))


36


¿Para Qué Sirven las Funciones?
  1. Reutilización de Código: Las funciones permiten escribir un bloque de código una vez y reutilizarlo en diferentes partes del programa, lo que reduce la duplicación y mejora la eficiencia.
  2. Organización y Legibilidad: Al dividir el código en funciones, se mejora la organización y la legibilidad del programa. Cada función puede tener un propósito específico, lo que facilita la comprensión del código.
  3. Facilidad de Mantenimiento: Si se necesita realizar cambios en la lógica de una tarea específica, solo es necesario modificar la función correspondiente, en lugar de buscar y cambiar el código en múltiples lugares.
  4. Abstracción: Las funciones permiten ocultar la complejidad de ciertas operaciones. Los usuarios de la función no necesitan conocer los detalles de su implementación, solo cómo llamarla y qué esperar como resultado.
  5. Modularidad: Las funciones fomentan un enfoque modular en la programación, lo que facilita la colaboración en proyectos grandes y la integración de diferentes componentes.

#Tipos de Funciones
  1. Funciones Integradas (Built-in Functions): Python proporciona muchas funciones integradas, como print(), len(), sum(), entre otras.
  2. Funciones Definidas por el Usuario: Son aquellas que los programadores crean para realizar tareas específicas.
  3. Funciones Anónimas (Lambdas): Son funciones pequeñas y sin nombre que se definen utilizando la palabra clave lambda. Se utilizan comúnmente para operaciones simples y se pueden pasar como argumentos a otras funciones.

In [27]:
suma = lambda x, y: x + y
print(suma(5,3))

8


#Lambda con condición

In [28]:
mayor = lambda x, y: x if x > y else y
print(mayor(10, 7))  # Resultado: 10

10


#Lambda para filtrar números pares

In [29]:
numeros = [1, 2, 3, 4, 5, 6]
pares = list(filter(lambda x: x % 2 == 0, numeros))
print(pares)  # Resultado: [2, 4, 6]

[2, 4, 6]


#Usando lambda con map: elevar cada número al cubo

In [30]:
numeros = [1, 2, 3, 4]
cubos = list(map(lambda x: x**3, numeros))
print(cubos)  # Resultado: [1, 8, 27, 64]

[1, 8, 27, 64]


#Estructuras de datos

<p  align="justify">En Python, los vectores y matrices son estructuras de datos que se utilizan para almacenar colecciones de elementos. Aunque Python no tiene un tipo de dato nativo específico para vectores y matrices, se pueden implementar utilizando listas, tuplas o, más comúnmente, utilizando bibliotecas como NumPy que están diseñadas para trabajar con datos numéricos de manera eficiente.</p>

##Vectores
<p  align="justify">Un vector es una estructura unidimensional que puede almacenar una colección de elementos, generalmente números. En Python, un vector se puede representar como una lista.</p>


In [31]:
vector = [1,2,3,4,5]
#es una lista pero con todos los datos del mismo tipo

##Iteración sobre un vector

In [32]:
for elemento in vector:
  print(elemento)

1
2
3
4
5


##Matrices
<p  align="justify">Una matriz es una estructura bidimensional que puede almacenar datos en filas y columnas. En Python, una matriz se puede representar como una lista de listas.</p>

In [33]:
matriz = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [34]:
#Accediendon a los elementos de la matriz
print(matriz[0][0]) #Sale 1
print(matriz[1][2]) #Sale 6

1
6


In [35]:
#Iteración sobre una matriz
for fila in matriz:
  for elemento in fila:
    print(elemento)

1
2
3
4
5
6
7
8
9


In [36]:
print(matriz)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [37]:
#Iteración sobre una matriz
for fila in matriz:
  for elemento in fila:
    print(elemento, end='\t')
  print()

1	2	3	
4	5	6	
7	8	9	



##Conjuntos
<p  align="justify">Los conjuntos (sets) en Python son una colección desordenada de elementos únicos. Esto significa que no pueden contener duplicados y no tienen un orden específico. Los conjuntos son útiles para realizar operaciones matemáticas como uniones, intersecciones y diferencias, y son especialmente eficientes para verificar la pertenencia de un elemento.</p>

Características de los Conjuntos
  1. Elementos Únicos: No se permiten duplicados. Si intentas agregar un elemento que ya existe, no se añadirá.
  2. Desordenados: No tienen un orden específico, lo que significa que no puedes acceder a los elementos por índice.
  3. Mutables: Puedes agregar y eliminar elementos después de que el conjunto ha sido creado.
  4. Soporte para Operaciones Matemáticas: Permiten realizar operaciones como unión, intersección y diferencia.

In [38]:
#Usando llaves
conjunto1 = {1,2,3,4,5}
#Usando la función set()
conjunto2 = set([3,4,5,6,7])
#conjunto vacio
conjunto_vacio = set()

In [39]:
#AGREGAMOS ELEMENTOS
conjunto = {1,2,3}

#agrega elemento
conjunto.add(4)
print(conjunto)

#Elimina un elemento
conjunto.remove(2)
print(conjunto)

#discard permite borrar elemento. Si este no existe, no manda mensaje de error
conjunto.discard(5)
print(conjunto)

{1, 2, 3, 4}
{1, 3, 4}
{1, 3, 4}


##Operaciones con Conjuntos
Los conjuntos permiten realizar varias operaciones matemáticas:
  1. Unión: Combina los elementos de dos conjuntos.
  2. Intersección: Obtiene los elementos comunes entre dos conjuntos.
  3. Diferencia: Obtiene los elementos que están en un conjunto pero no en el otro.
  4. Diferencia Simétrica: Obtiene los elementos que están en uno de los conjuntos, pero no en ambos.

In [40]:
#Operaciones con conjuntos

conjuntoA = {1,2,3}
conjuntoB = {3,4,5}

#Union
union = conjuntoA | conjuntoB
print(union)

#Interseccion
interseccion = conjuntoA & conjuntoB
print(interseccion)

#Diferencia
diferencia = conjuntoA - conjuntoB
print(diferencia)

#Diferencia simétrica
dif_simetrica = conjuntoA ^ conjuntoB
print(dif_simetrica)

{1, 2, 3, 4, 5}
{3}
{1, 2}
{1, 2, 4, 5}


##Diccionarios

<p align="justify">Los diccionarios en Python son una estructura de datos que permite almacenar pares de clave-valor. Son mutables, desordenados y permiten acceder a los valores a través de sus claves. Los diccionarios son muy útiles para organizar y gestionar datos de manera eficiente, especialmente cuando necesitas asociar un valor específico con una clave única.
Características de los Diccionarios</p>

 1. Pares Clave-Valor: Cada elemento en un diccionario se compone de una clave y un valor asociado. La clave debe ser única dentro del diccionario.
 2. Mutables: Puedes modificar, agregar o eliminar pares de clave-valor después de que el diccionario ha sido creado.
 3. Desordenados: No tienen un orden específico, lo que significa que no puedes acceder a los elementos por índice, sino por clave.
 4. Acceso Rápido: Permiten un acceso rápido a los valores a través de sus claves, lo que los hace eficientes para búsquedas.

In [41]:
#Creacion
diccionario = {
    "nombre": "Juan",
    "edad"  : 30,
    "ciudad": "Madrid"
}

diccionario2 = dict(nombre="Ana", edad=25, ciudad="Barcelona")

In [42]:
print(diccionario['nombre'])
print(diccionario['edad'])

Juan
30


In [43]:
for k,v in diccionario.items():
  print(f'{k}: {v}')

nombre: Juan
edad: 30
ciudad: Madrid


In [44]:
#Agregar y eliminar valores
diccionario["profesion"]="Ingeniero"
print(diccionario)

#eliminar un par clave-valor
del diccionario["ciudad"]
print(diccionario)

{'nombre': 'Juan', 'edad': 30, 'ciudad': 'Madrid', 'profesion': 'Ingeniero'}
{'nombre': 'Juan', 'edad': 30, 'profesion': 'Ingeniero'}


#Bibliotecas
<p align="justify">Las bibliotecas en Python son colecciones de módulos y paquetes que proporcionan funcionalidades específicas que pueden ser reutilizadas en diferentes programas. Estas bibliotecas permiten a los desarrolladores aprovechar código ya escrito y probado, lo que facilita el desarrollo de aplicaciones y reduce el tiempo de programación. Las bibliotecas pueden incluir funciones, clases y variables que ayudan a realizar tareas comunes, como manipulación de datos, acceso a bases de datos, creación de interfaces gráficas, procesamiento de imágenes, y mucho más.</p>

¿Para qué sirven las bibliotecas en Python?
  1. Reutilización de Código: Permiten a los desarrolladores reutilizar código existente, lo que ahorra tiempo y esfuerzo.
  2. Facilitan el Desarrollo: Proporcionan herramientas y funciones que simplifican tareas complejas, como el manejo de datos, la creación de gráficos, o la comunicación con APIs.
  3. Comunidad y Soporte: Muchas bibliotecas son mantenidas por comunidades activas, lo que significa que están constantemente mejoradas y actualizadas.
  4. Estandarización: Usar bibliotecas populares puede ayudar a estandarizar el desarrollo, lo que facilita la colaboración entre desarrolladores.

Tipos de Bibliotecas
  1. Bibliotecas Estándar: Vienen incluidas con Python y proporcionan funcionalidades básicas. Ejemplos incluyen math, datetime, os, sys, entre otros.
  2. Bibliotecas de Terceros: Son desarrolladas por la comunidad y pueden ser instaladas a través de herramientas como pip. Ejemplos incluyen NumPy, Pandas, Requests, Flask, Django, etc.

##Cómo usar bibliotecas en Python
1. Importar Bibliotecas

Para usar una biblioteca en tu código, primero debes importarla. Esto se hace utilizando la palabra clave import.

In [45]:
import math #biblioteca para usar varias funciones matemáticas

resultado = math.sqrt(16)
print(resultado)

4.0


In [46]:
import math

In [47]:
from math import sqrt

resultado = sqrt(25)
print(resultado)

5.0


3. Importar con Alias

Puedes asignar un alias a una biblioteca al importarla, lo que puede hacer que el código sea más legible o más corto.

In [48]:
import numpy as np #multiples funciones matemáticas para vectores

arreglo = np.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


#NumPy

<p align="justify">NumPy es una librería de Python especializada en el cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos.
Incorpora una nueva clase de objetos llamados arrays que permite representar colecciones de datos de un mismo tipo en varias dimensiones, y funciones muy eficientes para su manipulación.
La ventaja de Numpy frente a las listas predefinidas en Python es que el procesamiento de los arrays se realiza mucho más rápido (hasta 50 veces más) que las listas, lo cual la hace ideal para el procesamiento de vectores y matrices de grandes dimensiones.</p>

In [49]:
import numpy as np

In [50]:
arreglo = np.array([1,2,3,4,5])
print(arreglo)

print()
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]


2. Crear Arreglos con Funciones de NumPy
NumPy tiene varias funciones para crear arreglos de manera más eficiente:
  * np.zeros(shape): Crea un arreglo lleno de ceros.
  * np.ones(shape): Crea un arreglo lleno de unos.
  * np.arange(start, stop, step): Crea un arreglo con un rango de valores.
  * np.linspace(start, stop, num): Crea un arreglo con un número específico de valores igualmente espaciados.

In [51]:
zeros = np.zeros((2,3))
print(zeros)
print()

unos = np.ones((2,3))
print(unos)
print()

rango = np.arange(0,10,2)
print(rango)
print()

linspace = np.linspace(0,1,5)
print(linspace)

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]


In [52]:
#PROPIEDADES DE ARREGLOS
arreglo = np.array([[1,2,3],[4,5,6]])

print(arreglo.shape) #cantidad de filas y columnas
print(arreglo.ndim) #cuantas dimensiones tiene
print(arreglo.size) #cuantos elementos hay
print(arreglo.dtype) # Tipo de datos de los elementos

(2, 3)
2
6
int64


In [53]:
#OPERACIONES BASICAS

a = np.array([1,2,3])
b = np.array([4,5,6])

suma = a+b
print(f'Suma: {suma} \n')

resta = a-b
print(f'Resta: {resta} \n')

multiplicacion = a*b
print(f'Multiplicacion: {multiplicacion} \n')

division = a/b
print(f'Division: {division} \n')

potencia = a**2
print(f'Potencia: {potencia}')

Suma: [5 7 9] 

Resta: [-3 -3 -3] 

Multiplicacion: [ 4 10 18] 

Division: [0.25 0.4  0.5 ] 

Potencia: [1 4 9]


##Pandas

Pandas es una librería de Python especializada en el manejo y análisis de estructuras de datos.
Las principales características de esta librería son:
  * Define nuevas estructuras de datos basadas en los arrays de la librería NumPy pero con nuevas funcionalidades.
  * Permite leer y escribir fácilmente ficheros en formato CSV, Excel y bases de datos SQL.
  * Permite acceder a los datos mediante índices o nombres para filas y columnas.
  * Ofrece métodos para reordenar, dividir y combinar conjuntos de datos.
  * Permite trabajar con series temporales.
  * Realiza todas estas operaciones de manera muy eficiente.

##Tipos de datos de Pandas
Pandas dispone de tres estructuras de datos diferentes:
  * Series: Estructura de una dimensión.
  * DataFrame: Estructura de dos dimensiones (tablas).
  * Panel: Estructura de tres dimensiones (cubos).

Estas estructuras se construyen a partir de arrays de la librería NumPy, añadiendo nuevas funcionalidades.

###La clase de objetos Series

Son estructuras similares a los arrays de una dimensión. Son homogéneas, es decir, sus elementos tienen que ser del mismo tipo, y su tamaño es inmutable, es decir, no se puede cambiar, aunque si su contenido.
Dispone de un índice que asocia un nombre a cada elemento de la serie, a través de la cuál se accede al elemento.

{"A1":"Matemáticas", "A2":"Economía", "A3":"Programación"}

##Creación de Dataframe desde cero
Podemos crear Dataframe de diferentes maneras pero tres de las más utilizadas son:

**Diccionario**

In [54]:
import pandas as pd

diccionario = [{"name":"David","surname":"Suarez","age":32},{"name":"Gema","surname":"Parreño","age":31}]
employees = pd.DataFrame(diccionario,columns=["name","surname","age"])
print(employees)

    name  surname  age
0  David   Suarez   32
1   Gema  Parreño   31


##CSV para el ejemplo


```
ID,Nombre,Edad,Curso,Calificacion
1,Ana López,22,Matemáticas,85
2,Carlos Ruiz,21,Física,78
3,María García,23,Química,92
4,Juan Pérez,20,Biología,88
5,Laura Díaz,19,Historia,76
```



In [68]:
# Crear un DataFrame con los datos
data = {
    "ID": [1, 2, 3, 4, 5],
    "Nombre": ["Ana López", "Carlos Ruiz", "María García", "Juan Pérez", "Laura Díaz"],
    "Edad": [22, 21, 23, 20, 19],
    "Curso": ["Matemáticas", "Física", "Química", "Biología", "Historia"],
    "Calificacion": [85, 78, 92, 88, 76]
}

df = pd.DataFrame(data)

# Guardar el DataFrame como un archivo CSV
df.to_csv('estudiantes.csv', index=False)

print("Archivo estudiantes.csv creado exitosamente.")

Archivo estudiantes.csv creado exitosamente.


In [60]:
df = pd.read_csv('estudiantes.csv')
df.head()

ID        Nombre  Edad        Curso  Calificacion
0   1     Ana López    22  Matemáticas            85
1   2   Carlos Ruiz    21       Física            78
2   3  María García    23      Química            92
3   4    Juan Pérez    20     Biología            88
4   5    Laura Díaz    19     Historia            76

In [61]:
#AGREGAR COLUMNAS
df['acredita']=['si','si','si','si','si']

In [62]:
df.head()

ID        Nombre  Edad        Curso  Calificacion acredita
0   1     Ana López    22  Matemáticas            85       si
1   2   Carlos Ruiz    21       Física            78       si
2   3  María García    23      Química            92       si
3   4    Juan Pérez    20     Biología            88       si
4   5    Laura Díaz    19     Historia            76       si

In [63]:
#Filtrar datos
df_filtrado = df[df['Calificacion']>=80]
df_filtrado.head()

ID        Nombre  Edad        Curso  Calificacion acredita
0   1     Ana López    22  Matemáticas            85       si
2   3  María García    23      Química            92       si
3   4    Juan Pérez    20     Biología            88       si

In [64]:
#Agregar nuevo registro
df = df._append({"ID":6,"Nombre":"Adrian Diaz","Curso":"Bioquímica","Calificacion":50,"acredita":"no"}, ignore_index=True)
df = df._append({"ID":6,"Nombre":"Damian Alfaro","Curso":"Arquitectura","Calificacion":52,"acredita":"no"}, ignore_index=True)
df.head(10)

ID         Nombre  Edad         Curso  Calificacion acredita
0   1      Ana López  22.0   Matemáticas            85       si
1   2    Carlos Ruiz  21.0        Física            78       si
2   3   María García  23.0       Química            92       si
3   4     Juan Pérez  20.0      Biología            88       si
4   5     Laura Díaz  19.0      Historia            76       si
5   6    Adrian Diaz   NaN    Bioquímica            50       no
6   6  Damian Alfaro   NaN  Arquitectura            52       no

In [65]:
df_agrupado = df.groupby('acredita')['Calificacion'].mean()
df_agrupado.head()

acredita
no    51.0
si    83.8
Name: Calificacion, dtype: float64

In [66]:
#GUARDANDO CSV MODIFICADO
df.to_csv('nuevoNombre.csv', index=False)

Resumen
  * Carga de Datos: Utiliza pd.read_csv() para cargar un archivo CSV.
  * Transformaciones: Puedes agregar columnas, filtrar datos, agrupar y renombrar columnas.
  * Guardar Resultados: Usa to_csv() para guardar el DataFrame modificado en un nuevo archivo CSV.
  
Este flujo de trabajo básico te permite manejar y transformar datos de manera efectiva utilizando pandas.

#Actividad

<p align="justify" style="font-size:18px">Crear un data frame en pandas para almacenar el nombre, dirección, teléfono y percepción mensual de almenos 10 empleados durante un año. Los identificadores de las columnas serán como se indica a continuación: [nombre,direccion,telefono,enero,febrero,marzo...diciembre].

</br></br>
Utilizando las diferentes herramientas de programación (estructuras de control) calcular el monto mensual y la retención del ISR anual de cada empleado.</p>

Considere salarios entre  18,837.38 y   38,775.38

Ejemplo:
Si ganas $20,000 MXN al mes:

* Tu ingreso cae entre 18,837.38 y 38,775.38.

* Límite inferior: $18,837.38

* Excedente: $20,000 - $18,837.38 = $1,162.62

* Porcentaje: 23.52%

* ISR = (0.2352 × $1,162.62) ≈ $ esa multiplicacion

In [82]:
import pandas as pd
import numpy as np

# Datos de ejemplo
empleados = [
    {"nombre": "Ana López",      "direccion": "Calle 1 #100", "telefono": "5551112233"},
    {"nombre": "Luis Pérez",     "direccion": "Calle 2 #200", "telefono": "5552223344"},
    {"nombre": "Miguel Torres",  "direccion": "Calle 3 #300", "telefono": "5553334455"},
    {"nombre": "Sofía García",   "direccion": "Calle 4 #400", "telefono": "5554445566"},
    {"nombre": "Carlos Ruiz",    "direccion": "Calle 5 #500", "telefono": "5555556677"},
    {"nombre": "Elena Reyes",    "direccion": "Calle 6 #600", "telefono": "5556667788"},
    {"nombre": "Mario Mendoza",  "direccion": "Calle 7 #700", "telefono": "5557778899"},
    {"nombre": "Paula Jiménez",  "direccion": "Calle 8 #800", "telefono": "5558889900"},
    {"nombre": "Arturo Lima",    "direccion": "Calle 9 #900", "telefono": "5559990011"},
    {"nombre": "Lucía Estrada",  "direccion": "Calle 10 #1000", "telefono": "5550001122"},
]

# Generar percepciones mensuales aleatorias dentro del rango
np.random.seed(0)
for emp in empleados:
    salario = np.round(np.random.uniform(18837.38, 38775.38), 2)
    for mes in ['enero','febrero','marzo','abril','mayo','junio',
                'julio','agosto','septiembre','octubre','noviembre','diciembre']:
        emp[mes] = salario

# Crear el DataFrame
df = pd.DataFrame(empleados)
print("DataFrame de empleados:\n")

df

DataFrame de empleados:



nombre       direccion    telefono     enero   febrero     marzo  \
0      Ana López    Calle 1 #100  5551112233  29779.62  29779.62  29779.62   
1     Luis Pérez    Calle 2 #200  5552223344  33096.83  33096.83  33096.83   
2  Miguel Torres    Calle 3 #300  5553334455  30855.28  30855.28  30855.28   
3   Sofía García    Calle 4 #400  5554445566  29701.26  29701.26  29701.26   
4    Carlos Ruiz    Calle 5 #500  5555556677  27284.21  27284.21  27284.21   
5    Elena Reyes    Calle 6 #600  5556667788  31715.22  31715.22  31715.22   
6  Mario Mendoza    Calle 7 #700  5557778899  27561.99  27561.99  27561.99   
7  Paula Jiménez    Calle 8 #800  5558889900  36617.55  36617.55  36617.55   
8    Arturo Lima    Calle 9 #900  5559990011  38050.89  38050.89  38050.89   
9  Lucía Estrada  Calle 10 #1000  5550001122  26482.44  26482.44  26482.44   

      abril      mayo     junio     julio    agosto  septiembre   octubre  \
0  29779.62  29779.62  29779.62  29779.62  29779.62    29779.62  29779.62   
1  33096.83  33096.83  33096.83  33096.83  33096.83    33096.83  33096.83   
2  30855.28  30855.28  30855.28  30855.28  30855.28    30855.28  30855.28   
3  29701.26  29701.26  29701.26  29701.26  29701.26    29701.26  29701.26   
4  27284.21  27284.21  27284.21  27284.21  27284.21    27284.21  27284.21   
5  31715.22  31715.22  31715.22  31715.22  31715.22    31715.22  31715.22   
6  27561.99  27561.99  27561.99  27561.99  27561.99    27561.99  27561.99   
7  36617.55  36617.55  36617.55  36617.55  36617.55    36617.55  36617.55   
8  38050.89  38050.89  38050.89  38050.89  38050.89    38050.89  38050.89   
9  26482.44  26482.44  26482.44  26482.44  26482.44    26482.44  26482.44   

   noviembre  diciembre  
0   29779.62   29779.62  
1   33096.83   33096.83  
2   30855.28   30855.28  
3   29701.26   29701.26  
4   27284.21   27284.21  
5   31715.22   31715.22  
6   27561.99   27561.99  
7   36617.55   36617.55  
8   38050.89   38050.89  
9   26482.44   26482.44

In [84]:
# Función para calcular ISR mensual
def calcular_isr(salario_mensual):
    limite_inferior = 18837.38
    porcentaje = 0.2352
    if salario_mensual > limite_inferior:
        excedente = salario_mensual - limite_inferior
        isr = porcentaje * excedente
    else:
        isr = 0
    return isr

# Calcular ISR mensual y total anual para cada empleado
isr_mensual = []
isr_anual = []
monto_anual = []

for idx, row in df.iterrows():
    total_anual = 0
    total_isr = 0
    for mes in ['enero','febrero','marzo','abril','mayo','junio',
                'julio','agosto','septiembre','octubre','noviembre','diciembre']:
        salario = row[mes]
        total_anual += salario
        total_isr += calcular_isr(salario)
    monto_anual.append(total_anual)
    isr_mensual.append(calcular_isr(row['enero']))  # ISR de enero representa el mensual (todos los meses igual en este ejemplo)
    isr_anual.append(total_isr)

df['monto_anual'] = monto_anual
df['ISR_mensual'] = isr_mensual
df['ISR_anual'] = isr_anual

print("\nDataFrame con ISR:\n")

df[['nombre', 'monto_anual', 'ISR_mensual', 'ISR_anual']]


DataFrame con ISR:



nombre  monto_anual  ISR_mensual     ISR_anual
0      Ana López    357355.44  2573.614848  30883.378176
1     Luis Pérez    397161.96  3353.822640  40245.871680
2  Miguel Torres    370263.36  2826.610080  33919.320960
3   Sofía García    356415.12  2555.184576  30662.214912
4    Carlos Ruiz    327410.52  1986.694416  23840.332992
5    Elena Reyes    380582.64  3028.867968  36346.415616
6  Mario Mendoza    330743.88  2052.028272  24624.339264
7  Paula Jiménez    439410.60  4181.895984  50182.751808
8    Arturo Lima    456610.68  4519.017552  54228.210624
9  Lucía Estrada    317789.28  1798.118112  21577.417344